name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7eccb76e706decfa8ff57641a0a1afcaa7a2d2d8d175abc5c2740aa86c4b4d0b"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
