name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2519bc95fc000b4019297d672798f2fe87b2e950fa392c56192416bf2c8fd952"

[versions]
forge = "40.1.19"
minecraft = "1.18.2"
