name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b011d7ad2f722560d8b6c1cc410a96985af2aa02f2b51058b52b8182c70df76d"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
