name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be1f13df703165099c3700fb197f55f67c83e9ee5296906c8a7ffa3ff79e2029"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
