name = "The Power of Fiendship"
author = "Yours truly"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dc9568f8c3733a89db19a04a5cc056ea79011a5e4983fa8a96c7661d9691224"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
