name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad5de432027443408904e81160fa20d2b07458eb698ab139432827ecde56fd0d"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
