name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be8bbdbb3789578f398fde056b8d948d3ded960a04c7bbcd47104b6909f257de"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
