name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8fdc5e475986b1a6e3ad31bc20bf3d3acfecb53a44d8b10720648da9dc3a499"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
