name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f5e4d703e3dddb92abfb5b5b42c2bab591754ecbc61e3f00a72e86d94a07bde"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
