name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad638bde6820863c0bebf0a629c3e5ee0fc0c8ba5e9c295615ca7ed3ca86e6e0"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
