name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1853776a1cfec0fbf33a1d44f92812b1403fe13fdfefa8eda6b8a01cfc5afab"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
