name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed4be0bb555fc7c87cc8ead6330c0061ed12dc1267aedfdfb55957de08185e17"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
