name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d3fa91f5339c714240f47cab7f4a56267601d7aba6eb48c76441613c705d8c5"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
