name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "855d5309740515ee1b86ba6e017086b96e217e81c0abcc20dbd200f4ded296ed"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
