name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1ffa60a54c3a7eaa7689380ed9b962c89059375f88af428ceb6b867824bd878"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
