name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3c9203ecbdb06e4c65fa40aece01531d48c3b29aeedbf280ae1b0e6e6965824"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
