name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93dad5a1664fd8524039c86d46eeb174851decee9da1df91648ac1a8682bbfd6"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
