name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "657d7cfa05a0f7368a69834782ae83a2512487724d760fdac74681cc49174aab"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
