name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "109b93f381eb04a2e77907a7ab6918ea39ff30021b3c39fbcf89a1ce777a0ae9"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
