name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a883de3d16c51a95fe784346f406c885e70a9ecb65efc681473b71531f6c8829"

[versions]
forge = "40.1.19"
minecraft = "1.18.2"
