name = "The Power of Fiendship"
author = "Yours truly"
version = "0.1.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae5b00e85ac4d5b0e73decdad5ebca123344c3967d427e09f71ba107d75ed7cd"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
