name = "Alex's Mobs"
filename = "alexsmobs-1.17.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3709/858/alexsmobs-1.17.5.jar"
hash-format = "sha1"
hash = "0ea6eb9ee547bb8bd7a71d6ecf127ac6983b156f"

[update]
[update.curseforge]
file-id = 3709858
project-id = 426558
