name = "Biomes O' Plenty"
filename = "BiomesOPlenty-1.18.2-16.0.0.111-universal.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "d8b9a4040ec26893b21cd6e549898340429383f8"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3794487
project-id = 220318
