name = "Biomes O' Plenty"
filename = "BiomesOPlenty-1.18.2-16.0.0.109-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3759/236/BiomesOPlenty-1.18.2-16.0.0.109-universal.jar"
hash-format = "sha1"
hash = "760d09f3c530eb9dd1cf5d3c908ca922b3270c17"

[update]
[update.curseforge]
file-id = 3759236
project-id = 220318
