name = "Bookshelf"
filename = "Bookshelf-Forge-1.18.2-13.0.14.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "7f379f9820a34a3e6fec535d5fdc036a578ae00e"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3803196
project-id = 228525
