name = "Bookshelf"
filename = "Bookshelf-Forge-1.18.2-13.2.19.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "188fdf83cfcfb165c66f92c933f6593cdd8fc240"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3820189
project-id = 228525
