name = "CC: Tweaked"
filename = "cc-tweaked-1.18.2-1.100.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3709/268/cc-tweaked-1.18.2-1.100.4.jar"
hash-format = "sha1"
hash = "d31cf5cd49f0a7a437ad13813321ffa9caf3dd7b"

[update]
[update.curseforge]
file-id = 3709268
project-id = 282001
