name = "Chunky Pregenerator (Forge)"
filename = "Chunky-1.2.164.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3579/662/Chunky-1.2.164.jar"
hash-format = "sha1"
hash = "7b5b160f9378af5218bf22c9ec61d623a65e4eae"

[update]
[update.curseforge]
file-id = 3579662
project-id = 485681
