name = "Citadel"
filename = "citadel-1.11.2-1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3732/360/citadel-1.11.2-1.18.2.jar"
hash-format = "sha1"
hash = "e1455c255ed2495fe5fcbea98ef6f271beb1d043"

[update]
[update.curseforge]
file-id = 3732360
project-id = 331936
