name = "Configured"
filename = "configured-1.5.3-1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3721/946/configured-1.5.3-1.18.2.jar"
hash-format = "sha1"
hash = "c6be107c43666391ea5e25e847df2b96c2230bc3"

[update]
[update.curseforge]
file-id = 3721946
project-id = 457570
