name = "Connectible Chains [FORGE]"
filename = "Connectible Chains-forge-1.18.2-2.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3682/482/Connectible%20Chains-forge-1.18.2-2.1.0.jar"
hash-format = "sha1"
hash = "a3b6b89028e5a6c4748bd976b75abc691628e3aa"

[update]
[update.curseforge]
file-id = 3682482
project-id = 418514
