name = "Ding"
filename = "Ding-1.18-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3548/400/Ding-1.18-1.3.0.jar"
hash-format = "sha1"
hash = "63844f850fe57b70762ecb2a92359598ec71b871"

[update]
[update.curseforge]
file-id = 3548400
project-id = 231275
