name = "Double Doors (Forge)"
filename = "doubledoors_1.18.2-3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/532/doubledoors_1.18.2-3.3.jar"
hash-format = "sha1"
hash = "e692c429d9358ee4e63745803e95c8725e9fccaf"

[update]
[update.curseforge]
file-id = 3672532
project-id = 348831
