name = "Dramatic Doors"
filename = "DramaticDoors-1.18.2-1.6.3.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "6a812c1299ac918374d86f7416da0148e737e6ae"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3790182
project-id = 380617
