name = "Dramatic Doors"
filename = "DramaticDoors-1.18.2-1.6.4.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "100c344517afb024fe124a3c98e89ac56635667e"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3807802
project-id = 380617
