name = "Dramatic Doors"
filename = "DramaticDoors-1.18.2-1.5.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3692/441/DramaticDoors-1.18.2-1.5.3.jar"
hash-format = "sha1"
hash = "63ac416c1d525061a01956e4b88306b413fe0753"

[update]
[update.curseforge]
file-id = 3692441
project-id = 380617
