name = "Global Data- & Resourcepacks"
filename = "global_packs-fabric-1.18.2-1.12.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "b98393cf3e0635851b94e0e69f6d82e78c2a3609"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3805446
project-id = 317134
