name = "Global Data- & Resourcepacks"
filename = "Global Data-  Resourcepacks-forge-1.18.2-1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3680/994/Global%20Data-%20%20Resourcepacks-forge-1.18.2-1.12.jar"
hash-format = "sha1"
hash = "ac22c3237adf01db2ad746e8749ce1c6db1d9629"

[update]
[update.curseforge]
file-id = 3680994
project-id = 317134
