name = "Easy Magic [Forge]"
filename = "EasyMagic-v3.3.0-1.18.2-Forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/353/EasyMagic-v3.3.0-1.18.2-Forge.jar"
hash-format = "sha1"
hash = "cbc3b613aa55c4a698b4d4e50ea54f192ac90f02"

[update]
[update.curseforge]
file-id = 3671353
project-id = 456239
