name = "Ecologics"
filename = "ecologics-FORGE-1.18.2-1.6.7.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "1866d13af4ad059984585fe5ff0775d91ae382ec"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3804127
project-id = 570463
