name = "Ecologics"
filename = "ecologics-FORGE-1.18.2-1.6.6.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "1186ce105c0de5da0e79ad35b2dce47c170704e6"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3800676
project-id = 570463
