name = "Ecologics"
filename = "ecologics-FORGE-1.18.2-1.6.8.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "b8f5d3b95abce09775bc6aa3661df0b463fe5e80"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3810999
project-id = 570463
