name = "Effortless Building"
filename = "effortlessbuilding-1.18-2.34.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3704/104/effortlessbuilding-1.18-2.34.jar"
hash-format = "sha1"
hash = "5bb527c7850217221d442b9f7122d969d3670b39"

[update]
[update.curseforge]
file-id = 3704104
project-id = 302113
