name = "Enchant With Mob"
filename = "enchantwithmob-1.18.2-4.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3770/32/enchantwithmob-1.18.2-4.1.0.jar"
hash-format = "sha1"
hash = "fed38d8f87ebc27d7438e96bfa8b611d8edb8d92"

[update]
[update.curseforge]
file-id = 3770032
project-id = 391187
