name = "Enchant With Mob"
filename = "enchantwithmob-quilt-1.0.0+1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "ef7d2a26980496edc397bedcfe41db001466b235"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3820481
project-id = 391187
