name = "Eyes in the Darkness"
filename = "EyesInTheDarkness-1.18.2-1.2.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/755/EyesInTheDarkness-1.18.2-1.2.5.jar"
hash-format = "sha1"
hash = "667bbdd62729d82f292342cfa319825055c772fe"

[update]
[update.curseforge]
file-id = 3670755
project-id = 304719
