name = "ForgeEndertech"
filename = "ForgeEndertech-1.18.2-9.0.1.0-build.0767.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3777/164/ForgeEndertech-1.18.2-9.0.1.0-build.0767.jar"
hash-format = "sha1"
hash = "22dd02dc4b22c0178a62d64846feca22f1f12353"

[update]
[update.curseforge]
file-id = 3777164
project-id = 244844
