name = "Friends&Foes (Forge)"
filename = "friendsandfoes-forge-mc1.18.2-1.4.1.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "aac74b3e65b26826b5faa75d25b520382cafaab9"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3808980
project-id = 602059
