name = "GeckoLib"
filename = "geckolib-quilt-1.18-3.0.6.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "12d8af20db402be6c37fa78a0854933e6b74e950"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3785982
project-id = 388172
