name = "I Know What I'm Doing (IKWID)"
filename = "IKnowWhatImDoing-5.0.0-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3561/102/IKnowWhatImDoing-5.0.0-forge.jar"
hash-format = "sha1"
hash = "43a95cd388d3874b54c57ad3845f0db59529d0f0"

[update]
[update.curseforge]
file-id = 3561102
project-id = 271492
