name = "I Like Wood - Biomes O' Plenty Plugin"
filename = "ilikewoodxbiomesoplenty-1.18.2-8.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3723/238/ilikewoodxbiomesoplenty-1.18.2-8.0.0.jar"
hash-format = "sha1"
hash = "88a3555b1eef5f3f96971d1590f88e917cbb6b59"

[update]
[update.curseforge]
file-id = 3723238
project-id = 437203
