name = "I Like Wood"
filename = "ilikewood-1.18.2-8.5.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3726/545/ilikewood-1.18.2-8.5.0.2.jar"
hash-format = "sha1"
hash = "794af6b863285ad2655ed3ed94e09f8f6c4ef973"

[update]
[update.curseforge]
file-id = 3726545
project-id = 324164
