name = "I Like Wood - Oh The Biomes You'll Go Plugin"
filename = "ilikewoodxbyg-1.18.2-8.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3723/239/ilikewoodxbyg-1.18.2-8.0.0.jar"
hash-format = "sha1"
hash = "46f077542e0ca703e38065b6cc9ef0d0e50cb2de"

[update]
[update.curseforge]
file-id = 3723239
project-id = 475110
