name = "Integrated Dungeons and Structures"
filename = "idas_forge-1.1.1+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3779/260/idas_forge-1.1.1+1.18.2.jar"
hash-format = "sha1"
hash = "66519f99ece45fb8fc098cb42998dab20e5f8812"

[update]
[update.curseforge]
file-id = 3779260
project-id = 605375
