name = "Integrated Dungeons and Structures"
filename = "idas_forge-1.1.6+1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "565f73c22d38a6527029ac0d46973a6b4c30282c"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3801337
project-id = 605375
