name = "Kiwi 🥝 (Forge)"
filename = "Kiwi-1.18.2-forge-6.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3755/791/Kiwi-1.18.2-forge-6.1.0.jar"
hash-format = "sha1"
hash = "de811080290541c838abf45c244d679ded0c9b15"

[update]
[update.curseforge]
file-id = 3755791
project-id = 303657
