name = "Little Logistics"
filename = "littlelogistics-mc1.18.2-v1.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3756/74/littlelogistics-mc1.18.2-v1.2.3.jar"
hash-format = "sha1"
hash = "0360cdd09404211fe71eaffc0092156277884354"

[update]
[update.curseforge]
file-id = 3756074
project-id = 570050
