name = "More Villagers"
filename = "morevillagers-FORGE-1.18.2-3.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3696/31/morevillagers-FORGE-1.18.2-3.2.0.jar"
hash-format = "sha1"
hash = "8f64b49acc9dc927733a59fc1017385c380060f8"

[update]
[update.curseforge]
file-id = 3696031
project-id = 484954
