name = "Neko's Enchanted Books"
filename = "NekosEnchantedBooks-1.18.2-1.7.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3780/211/NekosEnchantedBooks-1.18.2-1.7.0.jar"
hash-format = "sha1"
hash = "792b15de09a479abe8747bf965b916c8f4503e41"

[update]
[update.curseforge]
file-id = 3780211
project-id = 441114
