name = "Nether's Delight"
filename = "NethersDelight-1.18.2-2.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3756/127/NethersDelight-1.18.2-2.2.0.jar"
hash-format = "sha1"
hash = "8b3359629d6c5e6fe32c9cf94c00a0354304e770"

[update]
[update.curseforge]
file-id = 3756127
project-id = 496394
