name = "NetherPortalFix"
filename = "netherportalfix-forge-1.18-9.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/513/netherportalfix-forge-1.18-9.0.0.jar"
hash-format = "sha1"
hash = "85cba403b5671116aa688a54b825ea3edd2a7031"

[update]
[update.curseforge]
file-id = 3549513
project-id = 241160
