name = "Not Enough Crashes (Forge)"
filename = "notenoughcrashes-4.1.4+1.18.2-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3711/717/notenoughcrashes-4.1.4+1.18.2-forge.jar"
hash-format = "sha1"
hash = "8846da976179f209228a8b71f4b35b7afa5bd9ac"

[update]
[update.curseforge]
file-id = 3711717
project-id = 442354
