name = "Oh The Biomes You'll Go"
filename = "Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-21.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "73c9bf5c7916750af9ce342c0e6b76e1f56113d8"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3802788
project-id = 247560
