name = "Oh The Biomes You'll Go"
filename = "Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-11-all.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3775/362/Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-11-all.jar"
hash-format = "sha1"
hash = "57008b64ca121252249f6c04eba006a0fc1535db"

[update]
[update.curseforge]
file-id = 3775362
project-id = 247560
