name = "Ore Variants "
filename = "Ore_Variants_v2.3.zip"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3771/650/Ore_Variants_v2.3.zip"
hash-format = "sha1"
hash = "76ac439f82726a927c66707d704f35e83993b6ba"

[update]
[update.curseforge]
file-id = 3771650
project-id = 476719
