name = "Overweight Farming"
filename = "overweightfarming-1.18.2-1.3.2-forge.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "ba58da7565880808db002de02b4948eed7225b57"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3813212
project-id = 591666
