name = "Overweight Farming"
filename = "overweightfarming-1.18.2-1.3.0-forge.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "96bc4731a6b15cc882674b462c7b2d6a6ff78267"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3793669
project-id = 591666
