name = "Paragliders"
filename = "Paraglider-1.18.2-1.6.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3738/28/Paraglider-1.18.2-1.6.0.0.jar"
hash-format = "sha1"
hash = "4d2ec6b37d5816309f9052928d14501c0089d660"

[update]
[update.curseforge]
file-id = 3738028
project-id = 289240
