name = "Puzzles Lib [Forge]"
filename = "PuzzlesLib-v3.3.3-1.18.2-Forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3773/679/PuzzlesLib-v3.3.3-1.18.2-Forge.jar"
hash-format = "sha1"
hash = "ee81a2f68b6d128f9eea91aa85b11dbeb14bda05"

[update]
[update.curseforge]
file-id = 3773679
project-id = 495476
