name = "Radon"
filename = "radon-0.8.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3707/321/radon-0.8.1.jar"
hash-format = "sha1"
hash = "7f3ec8a8f7aaecd22f19922fd8aca2e559c4be9a"

[update]
[update.curseforge]
file-id = 3707321
project-id = 596879
