name = "Seeds : Sustainable World"
filename = "seeds-1.18.2-1.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3777/197/seeds-1.18.2-1.0.6.jar"
hash-format = "sha1"
hash = "2d3a1be42cb87befdced53477e8b74cfa4ecc264"

[update]
[update.curseforge]
file-id = 3777197
project-id = 601515
