name = "Selene Lib"
filename = "selene-1.18.2-1.16.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "f992954711fc2c9fcdb9612e7bad8845e392c6e6"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3802427
project-id = 499980
