name = "Selene Lib"
filename = "selene-1.18.2-1.15.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3778/802/selene-1.18.2-1.15.8.jar"
hash-format = "sha1"
hash = "e64cc62509665cc14918869514457bb01856c365"

[update]
[update.curseforge]
file-id = 3778802
project-id = 499980
