name = "Selene Lib"
filename = "selene-1.18.2-1.17.3.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "ecdf73f6d8a29f269d5fe395d4a23c4c1588a507"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3819295
project-id = 499980
