name = "Selene Lib"
filename = "selene-1.18.2-1.15.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3776/858/selene-1.18.2-1.15.7.jar"
hash-format = "sha1"
hash = "d670ab715b192f4ae3bd96a67f2fd0b08b6a3688"

[update]
[update.curseforge]
file-id = 3776858
project-id = 499980
