name = "ServerConfig Updater"
filename = "serverconfigupdater-2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3585/637/serverconfigupdater-2.0.jar"
hash-format = "sha1"
hash = "9b77b14548841e2d05025d9b403f30d1c3079113"

[update]
[update.curseforge]
file-id = 3585637
project-id = 365281
