name = "Server Tab Info"
filename = "ServerTabInfo-1.18.2-1.3.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3697/613/ServerTabInfo-1.18.2-1.3.5.jar"
hash-format = "sha1"
hash = "58f423b32c9a98201be8632268e8801cbfce8351"

[update]
[update.curseforge]
file-id = 3697613
project-id = 291788
