name = "Snowy Spirit"
filename = "snowyspirit-1.18.2-1.3.1.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "bfdbbef212cc0a17e5d4c9a82fdf3f2438e0da51"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3801243
project-id = 566142
