name = "Snow! Real Magic! ⛄ (Forge)"
filename = "SnowRealMagic-1.18.2-forge-4.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3680/622/SnowRealMagic-1.18.2-forge-4.0.0.jar"
hash-format = "sha1"
hash = "d2bd2b87c6eb48ea988e9c291aa34fb83a6018c3"

[update]
[update.curseforge]
file-id = 3680622
project-id = 308663
