name = "Snow! Real Magic! ⛄ (Forge)"
filename = "SnowRealMagic-1.18.2-forge-4.1.0.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "1b6062fd7560a15f5c40e7464b5f217cc974658a"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3804954
project-id = 308663
