name = "Spice of Life: Carrot Edition"
filename = "SoL-Carrot-1.18.1-1.12.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3571/539/SoL-Carrot-1.18.1-1.12.0.jar"
hash-format = "sha1"
hash = "c9dbb5e6129676fd157811a39542211d4af2af3a"

[update]
[update.curseforge]
file-id = 3571539
project-id = 277616
