name = "Stay True Modded Compats"
filename = "Stay True Compats v3 [1.18].zip"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3683/671/Stay%20True%20Compats%20v3%20%5B1.18%5D.zip"
hash-format = "sha1"
hash = "a18aed9583727d4a7424d949b6d40edb2b8cf7bb"

[update]
[update.curseforge]
file-id = 3683671
project-id = 576591
