name = "Structure Gel API"
filename = "structure_gel-1.18.2-2.2.4.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "c0ec3f8c077c7152c4abdf83c0fd031215d30542"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3797535
project-id = 378802
