name = "Structure Gel API"
filename = "structure_gel-1.18.2-2.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3764/568/structure_gel-1.18.2-2.2.2.jar"
hash-format = "sha1"
hash = "469d120a8237fc5e4ec033c5e746d689597b9d61"

[update]
[update.curseforge]
file-id = 3764568
project-id = 378802
