name = "Stylish Effects [Forge]"
filename = "StylishEffects-v3.1.0-1.18.2-Forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/298/StylishEffects-v3.1.0-1.18.2-Forge.jar"
hash-format = "sha1"
hash = "7e02224a36e0d67cdff35f2b847db8a2f675238b"

[update]
[update.curseforge]
file-id = 3671298
project-id = 543661
