name = "The Conjurer"
filename = "the-conjurer-1.18.2-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3749/502/the-conjurer-1.18.2-1.1.1.jar"
hash-format = "sha1"
hash = "1ad86aaa623754605dd46472bd8848422d4c5c29"

[update]
[update.curseforge]
file-id = 3749502
project-id = 377798
