name = "When Dungeons Arise - Forge!"
filename = "DungeonsArise-1.18.2-2.1.50c-beta.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3714/22/DungeonsArise-1.18.2-2.1.50c-beta.jar"
hash-format = "sha1"
hash = "dd3f3c41f7ed9412d260816c9187801a1f724878"

[update]
[update.curseforge]
file-id = 3714022
project-id = 442508
