name = "World Stripper"
filename = "World Stripper-1.18.2-3.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/854/World%20Stripper-1.18.2-3.1.0.jar"
hash-format = "sha1"
hash = "451973c08244fc1acef724fcf29e3cbf9e893082"

[update]
[update.curseforge]
file-id = 3670854
project-id = 250603
