name = "YDM's Glare"
filename = "glare-1-18-1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3675/523/glare-1-18-1.jar"
hash-format = "sha1"
hash = "4a34b6c59c17c2af9b5952d423b65f4132c2c421"

[update]
[update.curseforge]
file-id = 3675523
project-id = 589268
